import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  phaseContainer: {
    backgroundColor: '#1a1a1a',
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  phaseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#242424',
    paddingBottom: 12,
  },
  phaseTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#ffffff',
  },
  phaseActions: {
    flexDirection: 'row',
    gap: 12,
  },
  phaseActionButton: {
    backgroundColor: '#3d5afe',
    borderRadius: 12,
    padding: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  phaseActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '500',
  },
  taskListContainer: {
    marginTop: 12,
  },
  taskItem: {
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  draggingTask: {
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  taskHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: '#3d5afe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxCompleted: {
    backgroundColor: '#3d5afe',
  },
  taskTitleContainer: {
    flex: 1,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#ffffff',
    marginBottom: 4,
  },
  taskTime: {
    fontSize: 14,
    color: '#848484',
  },
  completedText: {
    textDecorationLine: 'line-through',
    color: '#848484',
  },
  expandedContent: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#242424',
  },
  titleInput: {
    fontSize: 16,
    padding: 12,
    backgroundColor: '#242424',
    borderRadius: 8,
    marginBottom: 12,
    color: '#ffffff',
  },
  timeInputsContainer: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
  },
  timeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    backgroundColor: '#242424',
    borderRadius: 8,
  },
  timeButtonText: {
    color: '#3d5afe',
    fontSize: 14,
  },
  descriptionInput: {
    fontSize: 16,
    padding: 12,
    backgroundColor: '#242424',
    borderRadius: 8,
    marginBottom: 12,
    minHeight: 80,
    color: '#ffffff',
  },
  removeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    backgroundColor: '#3a1a1a',
    borderRadius: 8,
  },
  removeButtonText: {
    color: '#ff4d4f',
    fontSize: 14,
    fontWeight: '500',
  },
  addButton: {
    backgroundColor: '#3d5afe',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    width: 120,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignSelf: 'flex-end',
    marginTop: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  addButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '600',
    marginLeft: 8,
  },
  bottomSpacing: {
    height: 100,
  },
  phaseHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#242424',
  },
  phaseHeaderText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#ffffff',
  },
  phaseContent: {
    padding: 16,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
  },
  phaseSubHeader: {
    fontSize: 16,
    color: '#848484',
    marginBottom: 8,
  },
  header: {
    fontSize: 22,
    fontWeight: '600',
    color: '#ffffff',
    marginBottom: 16,
  },
  highlightContainer: {
    // flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#242424',
    borderRadius: 12,
    marginBottom: 16,
  },
  highlightBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    flex: 1,
  },
  highlightText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
  },
  phaseContent: {
    padding: 16,
    backgroundColor: '#1a1a1a',
    borderRadius: 12,
    marginTop: 12,
  },
  
});

export default styles;