import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#171717", // Match Routine Builder Background
  },
  container: {
    flex: 1,
    backgroundColor: "#171717", // Dark theme
    paddingBottom: 60, // Space for bottom elements
  },
  scrollContainer: {
    padding: 16,
  },
  header: {
    fontSize: 28,
    fontWeight: "600",
    color: "#FFFFFF",
    padding: 20,
    paddingBottom: 10,
    marginBottom: 15,
  },
  subHeader: {
    fontSize: 18,
    fontWeight: "600",
    color: "#D1D5DB",
    marginBottom: 12,
  },
  inputContainer: {
    borderRadius: 12,
    padding: 16,
    marginBottom: 24,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  input: {
    backgroundColor: "#252525",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 20,
    fontSize: 16,
    lineHeight: 20,
    color: "#FFFFFF",
    width: "100%",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3.84,
    elevation: 5,
  },
  label: {
    fontSize: 16,
    color: "#D1D5DB",
    marginBottom: 8,
    fontWeight: "500",
  },
  dateContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 15,
  },
  dateButton: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#2E2E2E",
    borderRadius: 8,
    padding: 12,
    marginBottom: 16,
  },
  dateButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    marginLeft: 8,
  },
  generateButton: {
    backgroundColor: "#252525",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
  },
  generateButtonDisabled: {
    opacity: 0.7,
  },
  generateButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  daysContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 24,
  },
  dayButton: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: "#252525",
  },
  dayButtonSelected: {
    backgroundColor: "#3D5AFE",
  },
  dayButtonText: {
    color: "#848484",
    fontSize: 14,
    fontWeight: "600",
  },
  dayButtonTextSelected: {
    color: "#FFFFFF",
  },
  phaseContainer: {
    backgroundColor: "#2E2E2E",
    borderRadius: 8,
    marginBottom: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  phaseHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#242424",
  },
  phaseTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  phaseDuration: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 4,
  },
  phaseDate: {
    fontSize: 14,
    color: "#9CA3AF",
    marginTop: 2,
  },
  metricsContainer: {
    backgroundColor: "#252525",
    padding: 16,
    borderRadius: 8,
    marginBottom: 16,
  },
  metricsTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 8,
  },
  tasksContainer: {
    marginTop: 16,
  },
  tasksTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  headerContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#242424",
  },
  saveButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#4C5B6C",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  saveButtonText: {
    marginLeft: 8,
    fontSize: 16,
    color: "#FFFFFF",
  },
  taskItem: {
    backgroundColor: "#2E2E2E",
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2.84,
    elevation: 3,
  },
  taskHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    gap: 12,
  },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: "#3D5AFE",
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxCompleted: {
    backgroundColor: "#3D5AFE",
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: "500",
    color: "#D1D5DB",
    marginBottom: 4,
  },
  taskTime: {
    fontSize: 14,
    color: "#9CA3AF",
  },
  expandedContent: {
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: "#242424",
  },
  removeButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    padding: 12,
    backgroundColor: "#242424",
    borderRadius: 8,
  },
  removeButtonText: {
    color: "#FF4D4F",
    fontSize: 14,
    fontWeight: "500",
  },
  fixedHeader: {
    position: "relative",
    zIndex: 1,
    backgroundColor: "#1F1F1F",
    paddingHorizontal: 16,
  },
  bottomSpacing: {
    height: 100,
  },
});

export default styles;
